export const routes = {
  login: '/login',
  users: {
    report: '/users/report',
    detail: (userId: string) => `/users/${encodeURIComponent(userId)}`,
    create: '/users/new',
    edit: (userId: string) => `/users/${encodeURIComponent(userId)}/edit`,
  },
  jobs: {
    explorer: '/jobs',
    detail: (jobId: string) => `/jobs/${encodeURIComponent(jobId)}`,
    create: '/jobs/new',
    edit: (jobId: string) => `/jobs/${encodeURIComponent(jobId)}/edit`,
  },
  featureFlags: '/feature-flags',
  apiExplorer: '/api-explorer',
  localisations: '/localisations',
  skillCategories: '/skill-categories',
  jobCategories: '/job-categories',
  finance: {
    transactions: '/finance/transactions',
    transactionDetail: (txId: string) => `/finance/transactions/${encodeURIComponent(txId)}`,
    payouts: '/finance/payouts',
    settings: '/finance/settings',
  },
  reports: {
    users: '/reports/users',
    jobsFunnel: '/reports/jobs-funnel',
    jobsFunnelBreakdown: '/reports/jobs-funnel/breakdown',
    disputes: '/reports/disputes',
    disputeDetail: (disputeId: string) => `/reports/disputes/${encodeURIComponent(disputeId)}`,
    invoices: '/reports/invoices',
    invoicesList: '/reports/invoices/list',
    liquidity: '/reports/liquidity',
    matchSpeed: '/reports/match-speed',
    cancellations: '/reports/cancellations',
    bidOutcomes: '/reports/bid-outcomes',
    workerSupply: '/reports/worker-supply',
    workerLeaderboard: '/reports/worker-leaderboard',
    profileCompleteness: '/reports/profile-completeness',
    registrations: '/reports/registrations',
    engagement: '/reports/engagement',
    ratings: '/reports/ratings',
    categories: '/reports/categories',
    portfolio: '/reports/portfolio',
  },
} as const;
