---
domain: deployment
source_task: add-docker-railway-deploy.md
date: 2026-05-22
keywords: ["docker", "dockerfile", "railway", "deploy", "container", "next standalone", "reverse proxy", "next-intl proxy"]
---

## Extracted Knowledge

### Next.js standalone output — Docker COPY layout
`output: 'standalone'` in `next.config.ts` emits a self-contained runtime tree at `.next/standalone/` that includes `server.js` and only the `node_modules` actually required at runtime. The runner stage must copy:
- `.next/standalone` → `./` (becomes the working directory root, contains `server.js` and pruned `node_modules`)
- `.next/static` → `./.next/static` (Next does NOT bundle static assets into standalone)
- `public` → `./public` (only if the directory exists — admin has no `public/` yet, so this COPY was omitted)

Skipping the `.next/static` copy results in a server that 404s every JS/CSS chunk. This is the single most common standalone-output footgun.

Entrypoint is `node server.js` from the root of the copied standalone tree. Do NOT prefix the path (e.g. `node apps/web/server.js`) unless you're in a pnpm workspace — admin is a single-repo so the standalone tree lives directly at `/app/`.

### GitHub Packages auth in Docker
`.npmrc` referencing `${NODE_AUTH_TOKEN}` requires the token to be present in the env at `pnpm install` time, NOT baked into the image. Pattern:
1. `ARG NODE_AUTH_TOKEN` in the deps stage
2. `RUN NODE_AUTH_TOKEN="$NODE_AUTH_TOKEN" pnpm install --frozen-lockfile`
3. Multi-stage build — runner stage never sees the ARG, so the token cannot leak into the final image layers
4. Build invocation: `docker build --build-arg NODE_AUTH_TOKEN=$NODE_AUTH_TOKEN ...`

On Railway: set `NODE_AUTH_TOKEN` as a **build-scope** variable (not a regular service variable) so it's available during image build but not injected into the running container.

### pnpm in Docker via corepack
`RUN corepack enable && corepack prepare pnpm@9.12.0 --activate` pins the version explicitly. Relying on bare `corepack enable` requires a `packageManager` field in `package.json`; without it, corepack uses an arbitrary default. The admin `package.json` has no `packageManager` field, so explicit `corepack prepare` is mandatory.

### Railway container deployment
Minimal `railway.json` for a Dockerfile-built service:
```json
{
  "$schema": "https://railway.app/railway.schema.json",
  "build": { "builder": "DOCKERFILE", "dockerfilePath": "Dockerfile" },
  "deploy": { "restartPolicyType": "ON_FAILURE", "restartPolicyMaxRetries": 5 }
}
```
- Railway injects `PORT` at runtime; Next standalone's `server.js` reads `process.env.PORT` automatically, so EXPOSE in the Dockerfile is documentation only.
- Set `HOSTNAME=0.0.0.0` explicitly — Next standalone defaults to `localhost` in some setups, which makes the service unreachable from outside the container.
- `healthcheckPath` is optional; omit until an actual `/health` route exists. Setting it to `/` works but adds noise to logs.
- `preDeployCommand` runs once per deploy before the new container takes traffic — used by the backend for `prisma:deploy:full`; admin has no DB so it's omitted.

### .dockerignore essentials
Beyond the obvious `node_modules` / `.next` / `.git`:
- `.env*` with `!.env.example` — prevent secret leakage into the build context
- `.claude/` and `workflows/` — agentic flow files have no business in a production image
- `e2e/`, `playwright-report/`, `test-results/`, `*.tsbuildinfo` — test artifacts inflate build context and slow `COPY . .`

### HOSTNAME must be set in CMD, not ENV (Docker container quirk)
Docker sets `HOSTNAME` automatically at container runtime to the container's own hostname (random hex ID, or `--hostname` flag value, or whatever the orchestrator injects). **This runtime injection overrides `ENV HOSTNAME=…` declared in the Dockerfile.** The Dockerfile ENV is the build-time default; the runtime value wins.

Symptom in Next.js standalone:
- Deploy logs show only `Local: http://localhost:8080`, no `Network:` line
- `Ready in 0ms` (unusually fast — server isn't actually doing real network setup)
- Server binds to loopback only; Railway's TCP probe somehow still passes (race with the proxy?) so deploy shows "Active" but external requests time out

Fix: set HOSTNAME inline in the CMD instruction so it runs *after* Docker's runtime injection:
```dockerfile
CMD ["sh", "-c", "HOSTNAME=0.0.0.0 exec node server.js"]
```
The `exec` preserves PID 1 / signal handling. Do NOT rely on `ENV HOSTNAME=0.0.0.0` in the Dockerfile — silently ignored.

### Next.js / next-intl behind a reverse proxy — port in absolute redirect URLs
When Next.js standalone runs behind a reverse proxy (Railway, Cloud Run, Fly, any L7 proxy that terminates TLS upstream), absolute redirect URLs generated by Next or by `next-intl` middleware can include the container's **internal listening port** in the `Location` header:
```
Location: https://example.com:8080/en   ← :8080 is internal, not public
```
The browser then follows the redirect to a port that isn't exposed on the public IP → `ERR_TIMED_OUT`. Crucially, the container itself is healthy and responding to the initial request — the failure is on the *next* request, against the wrong port.

This bites hardest with `next-intl` because its middleware redirects `/` → `/{locale}` on every first visit, so EVERY user hits the broken Location.

Detection: `curl -v https://<public-host>/` returns 307 with an unexpected `:port` in Location. The container's logs look normal.

Fix: wrap the next-intl middleware and strip `url.port` from any Location header before responding:
```ts
const response = intlMiddleware(request);
const location = response.headers.get('location');
if (location) {
  try {
    const url = new URL(location);
    if (url.port) {
      url.port = '';
      response.headers.set('location', url.toString());
    }
  } catch { /* relative location — leave alone */ }
}
return response;
```

Alternative fix paths considered: `assetPrefix` (only for static assets), `experimental.trustHostHeader` (does not exist), changing the listening port to 443 (Railway disallows), forwarding `X-Forwarded-Port: 443` (Railway doesn't expose this knob). The middleware Location-strip is the cleanest surgical fix.

### Diagnostic flow for "Application failed to respond" / `ERR_TIMED_OUT` on Railway
Walked this gauntlet end-to-end; record the order it should be debugged in:
1. **Container exists** — Deployments tab status: `Active` / `Crashed` / `Building`.
2. **Container is listening on the right port** — deploy log shows `Network: 0.0.0.0:PORT`. Confirm PORT matches Railway service's "Target Port" (set per-domain under Networking).
3. **Public URL reachable at all** — try Railway-generated `*.up.railway.app` URL, not just the custom domain. Rules out DNS / cert / CNAME issues.
4. **`curl -v` from outside** — definitive. Tells you DNS / TCP / TLS / HTTP status. ERR_TIMED_OUT from a browser is ambiguous; curl is precise.
5. **Read the Location header** — if curl returns a 3xx, the Location is where the real bug usually hides for next-intl apps.

Order matters. We skipped step 4 twice and lost time guessing.

## Proposed Skill Content

A `deployment` skill would cover:
1. **Choosing a deploy target.** Decision tree: Vercel (Next-native, easy, opinionated) vs Railway (Docker, BYO infra, cheaper for always-on) vs k8s (custom orchestration, only when scale demands).
2. **Next.js standalone Dockerfile recipe.** Multi-stage layout, static + public COPY traps, port/hostname env vars.
3. **Private-registry auth in containers.** Build-arg + multi-stage isolation pattern so tokens don't end up in image layers.
4. **pnpm in containers.** corepack pin pattern, `--frozen-lockfile`, when to use `pnpm prune --prod` vs Next standalone's automatic pruning.
5. **Railway service config.** `railway.json` schema, build vs runtime variable scopes, `preDeployCommand` use cases, healthcheck wiring.
6. **Image hardening.** Non-root user (`addgroup -S app && adduser -S app -G app`), `NODE_ENV=production`, `NEXT_TELEMETRY_DISABLED=1`, no shell tools in runner stage.
